version: "3.8"

services:
  xui-extended-api:
    build: .
    container_name: xui-extended-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./config:/app/config
      - ./log:/app/log
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
