xui_database: /etc/x-ui/x-ui.db
API_KEY: 3bf3fef7d67ef4a2d04d5a9873a0abdebb73588104912ac78e4fbb71a2159be6
reload_delay: 5
xui:
  username: YOUR_USERNAME
  password: YOUR_PASSWORD
  port: 2052
  address: http://your-server-address.com
  inbounds:
    - 30
    - 34
port: 5594
