# API Key. Must be the same as the one set in request headers
# You can generate a new API key using the ./utils/generateAPIKey.js script if it hasn't been set automatically already
# Example API Key: 030161d643b237cbef1a61a5ec4ee424679f656bb33c6ddedac20d3727411462
API_KEY: "YOUR_API_KEY_HASH"

# Servers information for running server
# Address: Set the value to the servers IP or domain/subdomain that is pointed to that IP plus the panel port
# If you're using Cloudflare to manage subdomains, please remember to turn off the "Tunnel through cloudflare" option
# If you have SSL certificate, your address must start with https. Otherwise, it must be http
xui:
  address: "http://localhost:54321" # example address, replace with your own
  inbounds:
    - 30 # example inbound id, replace with your own
    - 34 # example inbound id, replace with your own