# Path to X-UIs' database
# If you haven't changed the path in X-UI settings, then don't change this
xui_database: /etc/x-ui/x-ui.db

# API access code
# Default password is "mypassword"
# you can change it in bots' management panel
accesscode: BUUpKWkFFRUFBRUlWWE5sY201aGJXVUJEQUFCQ0ZCaGMzTjNi

# Servers information for running server
# Username and Password:
# Enter the username and password that is used for the X-UI panel
# PORT:
# enter the port that X-UI panel is running on
# IP and Address:
# Set the value to the servers IP and a domain/subdomain that is pointed to that IP
# If you're using Cloudflare to manage subdomains, please remember to turn of the "Tunnel through cloudflare" option
# If you have SSL certificate, your address must start with https. Otherwise it must be http
xui:
  username: "mee6"
  password: "myboobies3410"
  port: 2052
  address: http://ir-server.powertik.ir
  inbounds:
    - 30
    - 34
    - 59
    - 61

# Specify the PORT that you want the controller to run
port: 5594
